// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhckokmjzbyinntclotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloY2tva21qemJ5aW5udGNsb3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTk0MDUsImV4cCI6MjA2NTczNTQwNX0.ZTfJDzg-O3Jv7KgEc9THag86EaYyYdPH2nc4ys92N9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);